### ISSUE TITLE
browser-plugin: fix full update handling

### ISSUE THREAD

**Issue by cloudburstwan** [r-ainbowroad/2023-minimap#19]

**Comment by cloudburstwan** [comment]
This is a problem? Since I wrote the code for this I'd personally like to resovle it. Could you explain how it's broken exactly? @fluttershydev

**Comment by fluttershydev** [comment]
I need to verify what happens, but when I did a full update after the browser had already received diff updates it did not appear to update the template.

**Comment by cloudburstwan** [comment]
I'll look into the issue for you

**Comment by fluttershydev** [comment]
This may actually be because the mqtt message went out before uploading to S3.

**Comment by fluttershydev** [comment]
Yeah, just verified that was the issue.
